### PR TITLE
DBSCAN implemented (and incanter facilities in HiKM corrected)

### PR DESCRIPTION
**Pull request by aw5au**

### CODE REVIEW

**Comment by aw5au** [comment]
DBSCAN implemented. Incanter facilities in Hierarchical KMeans corrected.

**Comment by bricef** [comment]
Hey @aw5au did you mean to close the pull request?

**Comment by aw5au** [comment]
I would guess not.

The screen wasn't telling me anything reassuring about job done so I hit 
another button and - losing the ability to care - decided to interpret 
closed as something like finalised.

Sorry.

Andrew

**Comment by aw5au** [comment]
I've redone it as #20.

Andrew

**Comment by bricef** [comment]
Well, it's merged as #20 now :)

**Pull request closed without merging**
